routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


$this->group(['middleware' => 'auth'], function () {
    Route::get('/clientes/remove/{id}', 'ClienteController@remove')->name('clientes.remove');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('clientes', 'ClienteController@register')->name('register');
    Route::resource('clientes', 'ClienteController');
	$this->get('clientes/pdf/{id}', 'ClienteController@download')->name('pdf');
	Route::post('documentos/{id}', 'ClienteController@documentos')->name('documentos');
	 Route::get('documentos/{id}', 'ClienteController@documentosdelete')->name('documentosdelete');
});
//Route::get('cliente', 'ClienteController@index')->name('cliente.cadastrar');
//Route::get('cliente', 'ClienteController@show')->name('show');
//Route::post('cliente', 'ClienteController@store')->name('cliente.cadastro');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $fillable = [
        'nome', 'dataNasc', 'compras',
    ];

    protected $table = 'cliente';


}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Contato;
use App\Endereco;
use App\Documnetos;
use App\Http\Requests\ContatoEnviarRequest;
use App\PessoaFisica;
use App\PessoaJuridica;
use Barryvdh\DomPDF\PDF;
use Illuminate\Http\Request;
use App\Cliente;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;

class ClienteController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $clientes = Cliente::all();
        $contatos = Contato::all();
        $pessoa = PessoaFisica::all();
        $juridica = PessoaJuridica::all();
        return view('clientes.index', compact('clientes', 'contatos', 'pessoa', 'juridica'));    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clientes.cadastrar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     *
     */



    public function store(Request $request)
    {
        $cliente = new Cliente();
        $cliente->nome = $request->post('nome');
        $cliente->dataNasc = $request->post('dataNasc');
        $cliente->compras = $request->post('compras');
        $cliente->image = $request->post('image');
        $cliente->save();
        $id = $cliente->id;
        $contato = new Contato();
        $contato->id_cliente = $id;
        $contato->foneFixo = $request->post('foneFixo');
        $contato->celular = $request->post('celular');
        $contato->foneRecado = $request->post('foneRecado');
        $contato->email = $request->post('email');
        $contato->save();
        $endereco = new Endereco();
        $endereco->id_cliente = $id;
        $endereco->cep = $request->post('cep');
        $endereco->rua = $request->post('rua');
        $endereco->numero = $request->post('numero');
        $endereco->cidade = $request->post('cidade');
        $endereco->bairro = $request->post('bairro');
        $endereco->complemento = $request->post('complemento');
        $endereco->estado = $request->post('estado');
        $endereco->pais = $request->post('pais');
        $endereco->save();
        $pessoaFisica = new PessoaFisica();
        $pessoaFisica->id_cliente = $id;
        $pessoaFisica->cpf = $request->post('cpf');
        $pessoaFisica->rg = $request->post('rg');
        $pessoaFisica->nacionalidade = $request->post('nacionalidade');
        $pessoaFisica->profissao = $request->post('profissao');
        $pessoaFisica->sexo = $request->post('sexo');
        $pessoaFisica->estadoCivil = $request->post('estadoCivil');
        $pessoaFisica->save();
        $pessoaJuridica = new PessoaJuridica();
        $pessoaJuridica->id_cliente = $id;
        $pessoaJuridica->cnpj = $request->post('cnpj');
        $pessoaJuridica->save();
        /*return redirect()
            ->back()
            ->with('message','Cliente Cadastrado com Sucesso!');*/
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
                $nome = $cliente->nome;
            $primeiroNome = explode(" ", $nome);
            $name = "foto_perfil_".$primeiroNome[0];
            $extension = $request->image->extension();
            $nameFile = "{$name}.{$extension}";
            $cliente->image = $nameFile;
            $pasta = $request->image->storeAs('uploads/avatar', $id);
            $upload = $request->image->move($pasta, $nameFile);
            if(!$upload)
                return redirect()
                    ->back()
                    ->with('error', 'Falha ao enviar a Imagem');
            $cliente->save();
        }
        return redirect()->back()->with('message','Cliente Cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $clientes = Cliente::find($id);
        $ident = $clientes['id'];
        $pessoa = PessoaFisica::where('id_cliente', '=', $ident)->firstOrFail();
        $juridicap = PessoaJuridica::where('id_cliente', '=', $ident)->firstOrFail();
        $contato = Contato::where('id_cliente', '=', $ident)->firstOrFail();
        $endereco = Endereco::where('id_cliente', '=', $ident)->firstOrFail();
        $documentos = Documnetos::all();
        return view('clientes.show', compact('clientes', 'pessoa', 'contato', 'endereco', 'juridicap','documentos'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cliente = Cliente::find($id);
        $ident = $cliente['id'];
        $pessoa = PessoaFisica::where('id_cliente','=',$ident)->firstOrFail();
        $contato = Contato::where('id_cliente','=',$ident)->firstOrFail();
        $juridica = PessoaJuridica::where('id_cliente','=',$ident)->firstOrFail();
        $endereco = Endereco::where('id_cliente','=',$ident)->firstOrFail();
        return view('clientes.edit', compact('cliente', 'pessoa', 'contato', 'endereco','juridica'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cliente = Cliente::find($id);
        $ident = $cliente['id'];
        $pessoa = PessoaFisica::where('id_cliente','=',$ident)->firstOrFail();
        $contato = Contato::where('id_cliente','=',$ident)->firstOrFail();
        $endereco = Endereco::where('id_cliente','=',$ident)->firstOrFail();
        $dados = $request->all();
        $cliente->update($dados);
        $pessoa->update($dados);
        $contato->update($dados);
        $endereco->update($dados);
        if(empty($cliente->image)) {
            if ($request->hasFile('image') && $request->file('image')->isValid()) {
                $nome = $cliente->nome;
                $primeiroNome = explode(" ", $nome);
                $name = "foto_perfil_" . $primeiroNome[0];
                $extension = $request->image->extension();
                $nameFile = "{$name}.{$extension}";
                $cliente->image = $nameFile;
                $pasta = $request->image->storeAs('uploads/avatar', $id);
                $upload = $request->image->move($pasta, $nameFile);
                if (!$upload)
                    return redirect()
                        ->back()
                        ->with('error', 'Falha ao enviar a Imagem');
            }
            $cliente->update($dados);
        }else{
            if ($request->hasFile('image') && $request->file('image')->isValid()) {
                $nome = $cliente->nome;
                $primeiroNome = explode(" ", $nome);
                $name = "foto_perfil_" . $primeiroNome[0];
                $extension = $request->image->extension();
                $nameFile = "{$name}.{$extension}";
                $cliente->image = $nameFile;
                $pasta = $request->image->storeAs('uploads/avatar', $id);
                $upload = $request->image->move($pasta, $nameFile);
                if (!$upload)
                    return redirect()
                        ->back()
                        ->with('error', 'Falha ao enviar a Imagem');
            }
        }
        return redirect()->route('clientes.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function register()
    {
        return view('clientes.register');
    }

    public function destroy($id)
    {
        Cliente::find($id)->delete();
        return redirect()->route('clientes.index');
    }


    public function remove($id)
    {
        $clientes = Cliente::find($id);
        $ident = $clientes['id'];
        $pessoa = PessoaFisica::where('id_cliente','=',$ident)->firstOrFail();
        $contato = Contato::where('id_cliente','=',$ident)->firstOrFail();
        $endereco = Endereco::where('id_cliente','=',$ident)->firstOrFail();
        return view('clientes.remove', compact('clientes', 'pessoa', 'contato', 'endereco'));
    }
	
	public function documentos (Request $request, $id)
    {

        $documento = new Documnetos();
        $documento->id_cliente = $request->post('id_cliente');
        $documento->nome = $request->post('nome');
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $nome = $documento->nome;
            $primeiroNome =  preg_replace('/[ -]+/' , '-' , $nome);
            $name = "documento-" . $primeiroNome;
            $extension = $request->image->extension();
            $nameFile = "{$name}.{$extension}";
            $documento->image = $nameFile;
            $pasta = $request->image->storeAs('uploads/avatar', $id);
            $upload = $request->image->move($pasta, $nameFile);
            if (!$upload)
                return redirect()
                    ->back()
                    ->with('error', 'Falha ao enviar a Imagem');

        }
        $documento->save();
        return redirect()
            ->back()
            ->with('message', 'Documento Cadastrado Com Sucesso');

    }
	
	  public function documentosdelete($id)
    {
       Documnetos::find($id)->delete();
        return redirect()->back()->with('message', 'Documento do Cliente Deletado');
    }

	
	
	public function download($id)
    {
        $clientes = Cliente::find($id);
        $ident = $clientes->id;
        $contato = Contato::where('id_cliente','=',$ident)->firstOrFail();
        $endereco = Endereco::where('id_cliente','=',$ident)->firstOrFail();
        $juridica = PessoaJuridica::where('id_cliente','=',$ident)->firstOrFail();

resources/views/clientes/index.blade.php
@extends('adminlte::page')

@section('title', 'Sistema Viva Turismo')
<link href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
@section('content_header')
@stop

@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{route('home')}}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        @for($i = 0; $i <= count(Request::segments()); $i++)
            <li>
                <a href="">{{Request::segment($i)}}</a>
                @if($i < count(Request::segments()) & $i > 0)
                    {!!'<i class="fa fa-angle-right"></i>'!!}
                @endif
            </li>
        @endfor
    </ul>
 <div class="container-fluid" style="background: white;padding: 10px;">
  <h1>Lista de Todos Clientes Cadastrados</h1>
  <table id="minhaTabela" style="background: white;">
      <thead>
      <tr>
          <th>Foto Perfil</th>
          <th>Nome</th>
          <th>E-mail</th>
          <th>Telefone</th>
          <th>Editar</th>
          <th>Deletar</th>
          <th>Visualizar</th>
      </tr>
      </thead>
      <tbody>
      @foreach($clientes as $cliente)
          <tr>
              <td>
                  @foreach($pessoa as $pessoas)
                      @if($pessoas->id_cliente == $cliente->id)
                  @if(!empty($cliente->image))
                        <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/".$cliente->id."/".$cliente->image) }}" alt="" style="width: 50px;height: 50px;">
                    @elseif($pessoas->sexo == 'Feminino')
                      <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/avatarf.png") }}" alt="" style="width: 50px;height: 50px;">
                      @elseif($pessoas->sexo == 'Masculino')
                      <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/avatar.jpg") }}" alt="" style="width: 50px;height: 50px;">
                  @elseif($pessoas->cpf == "")
                      <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/empresa.png") }}" alt="" style="width: 50px;height: 50px;">
                  @endif
                          @endif
                      @endforeach

              </td>
                 </td>
                   <td>{{ $cliente->nome }}</td>

                  <td>
                      <?php
                        foreach ($contatos as $contato){
                            if($cliente->id == $contato->id_cliente){
                                echo $contato->email;
                            }
                        }
                      ?>
                  </td>
                <td>
                    <?php
                    foreach ($contatos as $contato){
                        if($cliente->id == $contato->id_cliente){
                            echo $contato->celular;
                        }
                    }
                    ?>
                </td>

              <td style="text-align: center;"><a href="{{ route('clientes.edit', $cliente->id) }}"><i class="glyphicon glyphicon-pencil"></i></a></td>
              <td style="text-align: center;"><a href="{{ route('clientes.remove', $cliente->id) }}"><i class="glyphicon glyphicon-trash"></i></a></td>
              <td style="text-align: center;"><a href="{{ route('clientes.show', $cliente->id) }}"><i class="glyphicon glyphicon-eye-open"></i></a></td>
          </tr>
      @endforeach
      </tbody>
  </table>
 </div>
  <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
  <script>
      $(document).ready(function(){
          $('#minhaTabela').DataTable({
              "language": {
                  "lengthMenu": "Mostrando _MENU_ registros por página",
                  "zeroRecords": "Nada encontrado",
                  "info": "Mostrando página _PAGE_ de _PAGES_",
                  "infoEmpty": "Nenhum registro disponível",
                  "infoFiltered": "(filtrado de _MAX_ registros no total)"
              }
          });
      });
  </script>
   

@stop

resources/views/clientes/remove.blade.php
@extends('adminlte::page')

@section('title', 'Sistema Viva Turismo')
<link href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
@section('content_header')
@stop

@section('content')
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{route('home')}}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        @for($i = 0; $i <= count(Request::segments()); $i++)
            <li>
                <a href="">{{Request::segment($i)}}</a>
                @if($i < count(Request::segments()) & $i > 0)
                    {!!'<i class="fa fa-angle-right"></i>'!!}
                @endif
            </li>
        @endfor
    </ul>
    <div class="col-md-12" style="background: darkred;margin: 10px;text-align: center;border-radius: 5px;color: white;">
        <h2>Tem Centeza que deseja deletar esse Cliente?</h2>
    </div>
    <div class="container-fluid">
        <!-- Main content -->
        <div class="col-md-3">

            <div class="row">
                <div class="col-md-12">

                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            @if(!empty($clientes->image))

                                <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/".$clientes->id."/".$clientes->image) }}" alt="" style="width: 100px;height: 100px;">

                            @elseif(!empty($pessoa->cpf))
                                <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/avatar.jpg") }}" alt="" style="width: 100px;height: 100px;">
                            @else
                                <img class="profile-user-img img-responsive img-circle" id="uploadPreview" src="{{ url("uploads/avatar/empresa.png") }}" alt="" style="width: 100px;height: 100px;">
                            @endif

                            <h3 class="profile-username text-center">{{ $clientes['nome'] }}</h3>

                            <p class="text-muted text-center">Profissão: {{ $pessoa['profissao'] }}</p>

                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>Cpf/Cnpj</b> <a class="pull-right">{{ $pessoa['cpf'] }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Nacionalidade</b> <a class="pull-right">{{ $pessoa['nacionalidade'] }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Estado Civil</b> <a class="pull-right">{{ $pessoa['estadoCivil'] }}</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                    <!-- About Me Box -->

                    <!-- /.box -->
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="nav-tabs-custom">
                <div class="tab-content">
                    <div class="active tab-pane" id="activity">
                         <form method="post" action="{{ route('clientes.destroy', $clientes->id)  }}">
                            {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="DELETE">
                                        {{ csrf_field() }}
                        <!-- Post -->
                        <div class="post">
                            <div class="user-block">
                                @if(!empty($clientes->image))

                                    <img class="img-circle img-bordered-sm"  src="{{ url("uploads/avatar/".$clientes->id."/".$clientes->image) }}" alt="" >

                                @elseif(!empty($pessoa->cpf))
                                    <img class="img-circle img-bordered-sm"  src="{{ url("uploads/avatar/avatar.jpg") }}" alt="" >
                                @else
                                    <img class="img-circle img-bordered-sm"  src="{{ url("uploads/avatar/empresa.png") }}" alt="" >
                                @endif
                                <span class="username">
                          <a href="#">{{ $clientes->nome }}.</a>
                          <a href="#" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
                        </span>
                                <span class="description">Cliene cadastrado em {{ date( 'd/m/Y  H:m:s' , strtotime($clientes->created_at)) }}</span>
                            </div>
                            <!-- /.user-block -->
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Data de Nascimento: <i style="color: royalblue">{{ $clientes->dataNasc }}</i>
                            </p>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Compras: <i style="color: royalblue">{{ $clientes->compras }}</i>
                            </p>
                            <h3 style="text-align: center;">Contatos</h3>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Celular: <i style="color: royalblue">{{ $contato->foneCelular }}</i>
                            </p>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Telefone Fixo: <i style="color: royalblue">{{ $contato->foneFixo }}</i>
                            </p>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Telefone Para Recado: <i style="color: royalblue">{{ $contato->foneRecado }}</i>
                            </p>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Email: <i style="color: royalblue">{{ $contato->email }}</i>
                            </p>
                            <h3 style="text-align: center;">Endereço</h3>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                País: <i style="color: royalblue">{{ $endereco->pais }}</i>
                            </p>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Estado: <i style="color: royalblue">{{ $endereco->estado }}</i>
                            </p>
                            <p style="font-size: 18px;border-bottom: 1px solid #edecec;">
                                Cidade: <i style="color: royalblue">{{ $endereco->cidade }}</i>
                            </p>
                        </div>
                         <button type="submit" class="btn btn-danger">Remover</button>
                          <a href="{{ route('clientes.index') }}" class="btn btn-default">Voltar</a>
                         </form>
                    </div>
@stop